//
//  AppDetailPresenter.swift
//  KakaobankTest
//
//  Created by rowkaxl on 06/05/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppDetailPresentationLogic {
    func presentSomething(response: AppDetail.Something.Response)
}

class AppDetailPresenter: AppDetailPresentationLogic {
    weak var viewController: AppDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: AppDetail.Something.Response) {
        let viewModel = AppDetail.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}

