//
//  AppSearchModels.swift
//  KakaobankTest
//
//  Created by rowkaxl on 04/05/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxDataSources
import SwiftyJSON

enum AppSearch {
    // MARK: Use cases
    
    enum RecentHitory {
        struct Request {
            
        }
        struct Response {
            var recentHistoryModels: [RecentHistoryModel]
        }
        struct ViewModel {
            var sectionModels: [AppSearchBaseItemSection]
        }
    }
    
    enum SearchHitory {
        struct Request {
            var query: String
        }
        struct Response {
            var recentHistoryModels: [RecentHistoryModel]
        }
        struct ViewModel {
            var sectionModels: [AppSearchBaseItemSection]
        }
    }
    
    enum SearchAppStore {
        struct Request {
            var query: String
        }
        struct Response {
            var json: JSON
            var appInfoModels: [AppInfoModel]
        }
        struct ViewModel {
            var sectionModels: [AppSearchBaseItemSection]
        }
    }
}

struct RecentHistoryModel {
    
    /// 검색어
    var searchWord: String?
    /// 검색시간
    var date: Date?
    
    init(searchWord: String, date: Date) {
        self.searchWord = searchWord
        self.date = date
    }
}

enum AppSearchStatus {
    /// 검색전
    case searchNon
    /// 검색시작(키워드x)
    case searchStart
    /// 검색중(키워드o)
    case searching
    /// 검색완료(앱정보화면)
    case viewAppInfo
}

extension AppSearchStatus {
    
    var baseViewAlpha: CGFloat {
        
        switch self {
        case .searchNon: return 0.0
        case .searchStart: return 0.4
        case .searching, .viewAppInfo: return 1.0
        }
    }
    
    var tableViewAlpha: CGFloat {
        
        switch self {
        case .searchNon: return 0.0
        case .searchStart: return 0.0
        case .searching, .viewAppInfo: return 1.0
        }
    }
    
    var baseViewBackgroundColor: UIColor {
        
        switch self {
        case .searchNon: return .black
        case .searchStart: return .black
        case .searching, .viewAppInfo: return .white
        }
    }
}
