//
//  AppSearchRouter.swift
//  KakaobankTest
//
//  Created by rowkaxl on 04/05/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AppSearchRoutingLogic {
    func routeToAppDetail(segue: UIStoryboardSegue?)
}

protocol AppSearchDataPassing {
    var dataStore: AppSearchDataStore? { get }
}

class AppSearchRouter: NSObject, AppSearchRoutingLogic, AppSearchDataPassing {
    weak var viewController: AppSearchViewController?
    var dataStore: AppSearchDataStore?
    
    // MARK: Routing
    
    func routeToAppDetail(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let vc = segue.destination as! AppDetailViewController
            var ds = vc.router!.dataStore!
            passDataToAppDetail(source: dataStore!, destination: &ds)
        }
    }
    
    // MARK: Passing data
    
    func passDataToAppDetail(source: AppSearchDataStore, destination: inout AppDetailDataStore)
    {
        let selectedSection = viewController?.searchTv.indexPathForSelectedRow?.section
        destination.appInfoModel = source.appInfoModels?[selectedSection ?? 0] ?? AppInfoModel()
    }
}

