//
//  AppSearchInteractor.swift
//  KakaobankTest
//
//  Created by rowkaxl on 04/05/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppSearchBusinessLogic {
    func doSomething(request: AppSearch.Something.Request)
}

protocol AppSearchDataStore {
    //var name: String { get set }
}

class AppSearchInteractor: AppSearchBusinessLogic, AppSearchDataStore {
    var presenter: AppSearchPresentationLogic?
    var worker: AppSearchWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: AppSearch.Something.Request) {
        worker = AppSearchWorker()
        worker?.doSomeWork()
        
        let response = AppSearch.Something.Response()
        presenter?.presentSomething(response: response)
    }
}


