//
//  AppSearchModels.swift
//  KakaobankTest
//
//  Created by rowkaxl on 04/05/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift
import RxDataSources

enum AppSearch {
    // MARK: Use cases
    
    enum RecentHitory {
        struct Request {
            
        }
        struct Response {
            var recentHitoryModels: [RecentHitoryModel]
        }
        struct ViewModel {
            var recentHitoryModels: [RecentHitoryModel]
            var sectionModels: [AppSearchBaseItemSection]
        }
    }
}

struct RecentHitoryModel {
    
    var searchWord: String?
    var date: Date?
    
    init(searchWord: String, date: Date) {
        self.searchWord = searchWord
        self.date = date
    }
}

class RecentHistoryRealmItem: Object {
    
    @objc dynamic var searchWord: String = ""
    @objc dynamic var date: Date = Date()
}

enum AppSearchStatus {
    case searchNon
    case searchStart
    case searching
}

extension AppSearchStatus {
    
    var alpha: CGFloat {
        
        switch self {
        case .searchNon: return 0.0
        case .searchStart: return 0.5
        case .searching: return 1.0
        }
    }
}
