//
//  AppSearchWorker.swift
//  KakaobankTest
//
//  Created by rowkaxl on 04/05/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxCocoa
import RxSwift

class AppSearchWorker {
    
    func requestSearchAppStore(query: String) -> PrimitiveSequence<SingleTrait, APIResponseType> {
        return APIManager.request(target: .searchAppStore(query: query))
    }
}

