//
//  AppSearchPresenter.swift
//  KakaobankTest
//
//  Created by rowkaxl on 04/05/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppSearchPresentationLogic {
    func presentRecentHistory(response: AppSearch.RecentHitory.Response)
    func presentSearchWordHistory(response: AppSearch.SearchWordHitory.Response)
    func presentSearchAppStore(response: AppSearch.SearchAppStore.Response)
}

class AppSearchPresenter: AppSearchPresentationLogic {
    weak var viewController: AppSearchDisplayLogic?
    
    // MARK: Do something
    
    func presentRecentHistory(response: AppSearch.RecentHitory.Response) {
        let sectionModels = self.getRecentHistorySectionModel(recentHistoryModels: response.recentHistoryModels)
        let viewModel = AppSearch.RecentHitory.ViewModel(sectionModels: sectionModels)
        viewController?.displayRecentHistory(viewModel: viewModel)
    }
    
    func presentSearchWordHistory(response: AppSearch.SearchWordHitory.Response) {
        
        let sectionModels = self.getSearchWordHistorySectionModel(searchHistoryModel: response.searchHistoryModel)
        let viewModel = AppSearch.SearchWordHitory.ViewModel(sectionModels: sectionModels)
        viewController?.displaySearchWordHistory(viewModel: viewModel)
    }
    
    func presentSearchAppStore(response: AppSearch.SearchAppStore.Response) {
        let sectionModels = self.getSearchAppStoreSectionModel(appInfoModel: response.appInfoModels)
        let viewModel = AppSearch.SearchAppStore.ViewModel(sectionModels: sectionModels)
        viewController?.displaySearchAppStore(viewModel: viewModel)
    }
}

extension AppSearchPresenter {
    
    func getRecentHistorySectionModel(recentHistoryModels: [RecentHistoryModel]) -> [AppSearchBaseItemSection] {
        
        var sectionModels: [AppSearchBaseItemSection] = [
            AppSearchBaseItemSection(items: [AppSearchBaseItem(type: .recentWordTitle, object: RecentHistoryModel(searchWord: "최근 검색어", date: Date()))])
        ]
        
        for (index, item) in recentHistoryModels.enumerated() {
            
            guard index < 10 else { return sectionModels }
            sectionModels.append(
                AppSearchBaseItemSection(items: [
                    AppSearchBaseItem(type: .recentWordContent, object: item)
                ]))
        }
        
        return sectionModels
    }
    
    func getSearchWordHistorySectionModel(searchHistoryModel: [SearchHistoryModel]) -> [AppSearchBaseItemSection] {
        
        var sectionModels: [AppSearchBaseItemSection] = []
        
        for item in searchHistoryModel {
            sectionModels.append(
                AppSearchBaseItemSection(items: [
                    AppSearchBaseItem(type: .searchWordList, object: item)
                    ]))
        }
        
        return sectionModels
    }
    
    func getSearchAppStoreSectionModel(appInfoModel: [AppInfoModel]) -> [AppSearchBaseItemSection] {
        
        var sectionModels: [AppSearchBaseItemSection] = []
        
        for item in appInfoModel {
            sectionModels.append(
                AppSearchBaseItemSection(items: [
                    AppSearchBaseItem(type: .searchAppInfoList, object: item)
                ]))
        }
        
        return sectionModels
    }
}
