//
//  AppSearchPresenter.swift
//  KakaobankTest
//
//  Created by rowkaxl on 04/05/2019.
//  Copyright (c) 2019 rowkaxl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppSearchPresentationLogic {
    func presentSomething(response: AppSearch.Something.Response)
}

class AppSearchPresenter: AppSearchPresentationLogic {
    weak var viewController: AppSearchDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: AppSearch.Something.Response) {
        let viewModel = AppSearch.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}

